language: python

# python versions to test
python:
 - "2.7"
 - "3.2"
 - "3.3"
 - "3.4"

# install prerequisites and dependencies
install:
  - pip install pep8 coveralls nose-exclude
  - pip install git+https://github.com/davidchall/nrtest.git
  - pip install -e .

# run PEP-8 compliance test and unit tests
script:
  - pep8 nrtest testing
  - nosetests testing --verbose --exclude-test=nrtest.test.Test --with-coverage --cover-package=nrtest

# Submit data to coveralls
after_success:
  coveralls
